language: python
services:
  - docker

branches:
  only:
    - master
    - develop
    - /^feature\/\w+/
env:
  global:
    - AWS_LAMBDA_ALIAS_NAME=$(if [ "$TRAVIS_BRANCH" == 'master' ]; then echo Production; else echo Beta; fi)
    - DOCKER_IMAGE=fathens/docker-lambda-peeler:haskell

before_install:
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs
  - git lfs fetch

install:
  - sudo easy_install pip && sudo pip install awscli
  - docker pull $DOCKER_IMAGE

script:
  - docker run -v $(pwd):$(pwd) -w $(pwd) -e AWS_DEFAULT_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e PKG_CONFIG_PATH=/var/task/lib/pkgconfig -e LD_LIBRARY_PATH=/var/task/lib $DOCKER_IMAGE /bin/sh -c '(npm install || npm install) && npm run zip'
  - export VERSION=$(./lambda_update.sh Peeler:$AWS_LAMBDA_ALIAS_NAME build-config/$TRAVIS_REPO_SLUG/main.zip)

after_success:
  - curl -X POST -H "Authorization:token $GITHUB_OAUTH_TOKEN" https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs -d "{\"ref\":\"refs/tags/deploy/$VERSION\", \"sha\":\"$(git log HEAD -n1 --format=%H)\"}"
