language: node_js
node_js: 4.2

branches:
  only:
    - master
    - develop
    - /^feature\/\w+/
env:
  global:
    - FUNC_NAME='AmazonPAA'
    - ALIAS=$(if [ "$TRAVIS_BRANCH" == 'master' ]; then echo Production; else echo Beta; fi)

install:
  - sudo easy_install pip && sudo pip install awscli
  - gem install bundler --no-document
  - bundle install
  - (npm install || npm install) && export PATH="$(npm bin):$PATH"

script:
  - gulp pack
  - PRE=$(aws lambda get-alias --function-name $FUNC_NAME --name $ALIAS | ruby -e 'require "json"; puts JSON.load($stdin)["FunctionVersion"]')
  - aws lambda update-function-code --function-name $FUNC_NAME --zip-file fileb://main.zip --publish | tee result
  - VERSION=$(ruby -e 'require "json"; puts JSON.load(open("result"))["Version"]')
  - aws lambda update-alias --function-name $FUNC_NAME --name $ALIAS --function-version $VERSION
  - aws lambda update-alias --function-name $FUNC_NAME --name "${ALIAS}_pre" --function-version $PRE
  - curl -v -X POST -H "Authorization:token $GITHUB_OAUTH_TOKEN" https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs -d "{\"ref\":\"refs/tags/deploy/$VERSION\", \"sha\":\"$(git log HEAD -n1 --format=%H)\"}"
