language: node_js
node_js: 4.3

branches:
  only:
    - master
    - develop
    - /^feature\/\w+/
env:
  global:
    - FUNC_NAME='AmazonPAA'
    - ALIAS=$(if [ "$TRAVIS_BRANCH" == 'master' ]; then echo Production; else echo Beta; fi)

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install build-essential bsdtar
  - sudo apt-get install gcc-4.9 g++-4.9
  - sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - mkdir tmp && cd tmp && curl -L https://github.com/Itseez/opencv/archive/3.1.0.zip | bsdtar -xvf -
  - cd opencv-* && ls -la && mkdir build && cd build
  - cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=No -D CMAKE_INSTALL_PREFIX=$HOME/opencv ..
  - make && make install
install:
  - sudo easy_install pip && sudo pip install awscli
  - gem install json --no-document
  - PKG_CONFIG_PATH=$HOME/opencv/lib/pkgconfig/ npm install --prefix=$TRAVIS_BUILD_DIR/ opencv
  - (npm install || npm install) && export PATH="$(npm bin):$PATH"

script:
  - gulp pack
  - PRE=$(aws lambda get-alias --function-name $FUNC_NAME --name $ALIAS | ruby -e 'require "json"; puts JSON.load($stdin)["FunctionVersion"]')
  - aws lambda update-function-code --function-name $FUNC_NAME --zip-file fileb://main.zip --publish | tee result
  - VERSION=$(ruby -e 'require "json"; puts JSON.load(open("result"))["Version"]')
  - aws lambda update-alias --function-name $FUNC_NAME --name $ALIAS --function-version $VERSION
  - aws lambda update-alias --function-name $FUNC_NAME --name "${ALIAS}_pre" --function-version $PRE
  - curl -v -X POST -H "Authorization:token $GITHUB_OAUTH_TOKEN" https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs -d "{\"ref\":\"refs/tags/deploy/$VERSION\", \"sha\":\"$(git log HEAD -n1 --format=%H)\"}"
